# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect_api', '0003_votertoelection'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='election',
            name='start_date',
            field=models.CharField(default='', max_length=40),
        ),
    ]
