# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect_api', '0005_auto_20191124_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
