# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elect_api', '0006_election_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=6)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elect_api.Election')),
            ],
        ),
    ]
