# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elect_api', '0007_electionkey'),
        ('elect_api', '0008_auto_20191202_0011'),
    ]

    operations = [
    ]
