# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elect_api', '0009_merge_20191202_0041'),
        ('elect_api', '0009_merge_20191202_0045'),
    ]

    operations = [
    ]
